resources:
  pipelines:
    - pipeline: pipepack
      source: CI-Nuuvify-CommonPack
      trigger:
        branches:
          include: [qas]
        stages: [Build]
  repositories:
    - repository: templates
      type: git
      name: SharedKernel/pipelines-store
      endpoint: SharedKernel-Repos

      
variables:
  - template: variables/global.yml@templates

stages:
  - stage: "Deploy"
    displayName: "Deploy Artifactory"

    variables:
      - template: variables/qas.yml@templates

    jobs:
      - deployment: PushNupkg
        displayName: "Push Artifactory Nupkg"
        condition: ne(variables['Build.Reason'], 'PullRequest')

        environment: ${{ variables['deploymentEnv'] }}

        pool:
          vmImage: $(vmImageName)

        strategy:
          runOnce:
            deploy:

              steps:

                - task: ArtifactoryDotnetCore@1
                  displayName: "Publish nuget artifacts"
                  inputs:
                    command: "push"
                    artifactoryService: "SharedKernel-Nuget-Jfrog"
                    targetDeployRepo: "nuuve-nuget-local"
                    targetDeployPath: "qa"
                    pathToNupkg: "$(Pipeline.Workspace)/pipepack/drop/*.nupkg"
                    collectBuildInfo: true
                    buildName: "$(Build.DefinitionName)"
                    buildNumber: "$(Build.BuildNumber)"
                    includeEnvVars: true
